---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  ports:
  - port: 443
    targetPort: {{ .Values.service.listenPort }}
  selector:
    app: {{ .Values.name }}
