---
{{- $gcpProjectID := required "The .Values.workloadIdentity.gcpProjectID value is required" .Values.workloadIdentity.gcpProjectID }}
{{- $gcpSA := required "The .Values.workloadIdentity.gcpSA value is required" .Values.workloadIdentity.gcpSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
{{- if .Values.workloadIdentity.enabled }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $gcpSA }}@{{ $gcpProjectID }}.iam.gserviceaccount.com
{{- end }}